baseURL = "thesykstem.netlify.app"
languageCode = "en-us"
title = "the sykstem"
permalinks = ":slug"
# enableGitInfo = true
disableKinds = ["taxonomy", "taxonomyTerm", "term",]

[build]
  writeStats = true

[outputFormats]
  [outputFormats.JSON]
    name = "JSON"
    baseName = "index"
	isPlainText = true
	mediaType = "application/json"
	home = ["HTML", "RSS", "JSON"]

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    name = "women"
    url = "/women"
    weight = 1
  [[menu.main]]
	name = "men"
	url = "/men/"
	weight = 2
  [[menu.main]]
	name = "unisex"
	url = "/unisex/"
	weight = 3
  [[menu.main]]
	name = "sale"
	url = "/sale/"
	weight = 4
	
[module]
  [[module.mounts]]
	source = "images"
	target = "assets/images"

[Params]
  description = "bulmaboutique"
  logo = "images/banner.jpg"
  favicon = true

[params.cookies]
  enable = false

[Params.social]
  email = ""

[privacy]
  [privacy.disqus]
	disable = true
  [privacy.googleAnalytics]
	disable = true
  [privacy.instagram]
	disable = true
  [privacy.twitter]
	disable = true
  [privacy.vimeo]
	disable = false
	enableDNT = false
	simple = false
  [privacy.youtube]
	disable = false
	privacyEnhanced = true
	
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
	[markup.goldmark.extensions]
	  definitionList = true
	  footnote = true
	  linkify = true
	  strikethrough = true
	  table = true
	  taskList = true
	  typographer = true
	[markup.goldmark.parser]
	  autoHeadingID = true
	  autoHeadingIDType = "github"
	  [markup.goldmark.parser.attribute]
		block = false
		title = true
	[markup.goldmark.renderer]
	  hardWraps = false
	  unsafe = true
	  xhtml = false